# Generated by Django 4.1.2 on 2022-10-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_text_products_project_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='project_description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='project_name',
            new_name='product_name',
        ),
    ]
