# Generated by Django 4.1.2 on 2022-10-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_project_description_products_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address_icon',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_icon',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
