# Generated by Django 4.1.2 on 2022-10-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact_address_icon_contact_phone_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email_icon',
            field=models.FileField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_icon',
            field=models.FileField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_icon',
            field=models.FileField(upload_to='pics'),
        ),
    ]
