# Generated by Django 4.1.2 on 2022-10-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contact_email_contact_email_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(upload_to='pics')),
                ('logo_img', models.ImageField(upload_to='pics')),
                ('about_banner_img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_icon',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_icon',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_icon',
        ),
    ]
