# Generated by Django 4.1.2 on 2022-10-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_image_remove_contact_address_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_icon',
            field=models.FileField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='about_banner_img',
            field=models.FileField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='image',
            name='banner_img',
            field=models.FileField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='image',
            name='logo_img',
            field=models.FileField(upload_to='pics'),
        ),
    ]
