# Generated by Django 4.1.2 on 2022-10-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_contact_email_icon_alter_image_about_banner_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email_icon',
        ),
        migrations.AlterField(
            model_name='image',
            name='logo_img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
