# Generated by Django 4.1.2 on 2022-10-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_contact_email_icon_alter_image_logo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('whatsapp', models.URLField()),
            ],
        ),
    ]
