# Generated by Django 4.1.2 on 2022-10-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField()),
                ('banner_heading', models.TextField()),
                ('banner_text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.TextField(),
        ),
    ]
