# Generated by Django 4.1.2 on 2022-10-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_text_alter_products_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='banner_heading',
            field=models.CharField(max_length=100),
        ),
    ]
